/*CREAR BASE DE DATOS*/
CREATE DATABASE IF NOT EXISTS prb_impresiones;

CREATE USER 'rpa_konica'@'%' IDENTIFIED BY 'Bio$1984.';
GRANT ALL PRIVILEGES ON prb_impresiones.* TO 'rpa_konica'@'%' WITH GRANT OPTION;
CREATE USER 'powerbi'@'%' IDENTIFIED BY 'Power_19_6';
GRANT SELECT ON prb_impresiones.* TO 'powerbi'@'%' WITH GRANT OPTION;

SHOW GRANTS FOR 'rpa_konica'@'%';

CREATE TABLE IF NOT EXISTS 283_A1UF011003305(
  con_id INTEGER unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(50) DEFAULT 'SIN ASIGNAR',
  total_counter INTEGER UNSIGNED DEFAULT 0,
  total_large_size_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_originals_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter INTEGER UNSIGNED DEFAULT 0,
  copy_total_total INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_total INTEGER UNSIGNED DEFAULT 0,
  printer_total_total INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_total INTEGER UNSIGNED DEFAULT 0,
  scan_total_print INTEGER UNSIGNED DEFAULT 0,
  scan_scans INTEGER UNSIGNED DEFAULT 0,
  scan_fax_tx INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_scans INTEGER UNSIGNED DEFAULT 0,
  fecha_contador VARCHAR(20) DEFAULT '31/12/1900 11:59', 
  impresora VARCHAR(50) DEFAULT 'A1UF011003305',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS 223_A1UG011006937(
  con_id INTEGER unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(50) DEFAULT 'SIN ASIGNAR',
  total_counter INTEGER UNSIGNED DEFAULT 0,
  total_large_size_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_originals_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter INTEGER UNSIGNED DEFAULT 0,
  copy_total_total INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_total INTEGER UNSIGNED DEFAULT 0,
  printer_total_total INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_total INTEGER UNSIGNED DEFAULT 0,
  scan_total_print INTEGER UNSIGNED DEFAULT 0,
  scan_scans INTEGER UNSIGNED DEFAULT 0,
  scan_fax_tx INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_scans INTEGER UNSIGNED DEFAULT 0,
  fecha_contador VARCHAR(20) DEFAULT '31/12/1900 11:59', 
  impresora VARCHAR(50) DEFAULT 'A1UG011006937',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS 224e_A61H011006163(
  con_id INTEGER unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(50) DEFAULT 'SIN ASIGNAR',
  total_counter INTEGER UNSIGNED DEFAULT 0,
  total_large_size_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_originals_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter INTEGER UNSIGNED DEFAULT 0,
  duplex_print_counter INTEGER UNSIGNED DEFAULT 0,
  total_no_pages_output INTEGER UNSIGNED DEFAULT 0,
  copy_total_total INTEGER UNSIGNED DEFAULT 0,
  copy_total_full_color INTEGER UNSIGNED DEFAULT 0,
  copy_total_black INTEGER UNSIGNED DEFAULT 0,
  copy_total_2color INTEGER UNSIGNED DEFAULT 0,
  copy_total_single_color INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_total INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_full_color INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_black INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_2color INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_single_color INTEGER UNSIGNED DEFAULT 0,
  printer_total_total INTEGER UNSIGNED DEFAULT 0,
  printer_total_full_color INTEGER UNSIGNED DEFAULT 0,
  printer_total_black INTEGER UNSIGNED DEFAULT 0,
  printer_total_2color INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_total INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_full_color INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_black INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_2color INTEGER UNSIGNED DEFAULT 0,
  color_total_full_color INTEGER UNSIGNED DEFAULT 0,
  color_total_black INTEGER UNSIGNED DEFAULT 0,
  color_total_2color INTEGER UNSIGNED DEFAULT 0,
  color_total_single_color INTEGER UNSIGNED DEFAULT 0,
  color_large_size_full_color INTEGER UNSIGNED DEFAULT 0,
  color_large_size_black INTEGER UNSIGNED DEFAULT 0,
  color_large_size_2color INTEGER UNSIGNED DEFAULT 0,
  color_large_size_single_color INTEGER UNSIGNED DEFAULT 0,
  scan_total_print_full_color INTEGER UNSIGNED DEFAULT 0,
  scan_total_print_black INTEGER UNSIGNED DEFAULT 0,
  scan_total_scans INTEGER UNSIGNED DEFAULT 0,
  scan_total_fax_tx INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print_full_color INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print_black INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_scans INTEGER UNSIGNED DEFAULT 0,
  fecha_contador VARCHAR(20) DEFAULT '31/12/1900 11:59', 
  impresora VARCHAR(50) DEFAULT 'A61H011006163',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS 363_A1UE011015445(
  con_id INTEGER unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(50) DEFAULT 'SIN ASIGNAR',
  total_counter INTEGER UNSIGNED DEFAULT 0,
  total_large_size_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_originals_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter INTEGER UNSIGNED DEFAULT 0,
  copy_total_total INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_total INTEGER UNSIGNED DEFAULT 0,
  printer_total_total INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_total INTEGER UNSIGNED DEFAULT 0,
  scan_total_print INTEGER UNSIGNED DEFAULT 0,
  scan_scans INTEGER UNSIGNED DEFAULT 0,
  scan_fax_tx INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_scans INTEGER UNSIGNED DEFAULT 0,
  fecha_contador VARCHAR(20) DEFAULT '31/12/1900 11:59', 
  impresora VARCHAR(50) DEFAULT 'A1UE011015445',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS 223_A1UG011006937(
  con_id INTEGER unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(50) DEFAULT 'SIN ASIGNAR',
  total_counter INTEGER UNSIGNED DEFAULT 0,
  total_large_size_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_originals_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter INTEGER UNSIGNED DEFAULT 0,
  copy_total_total INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_total INTEGER UNSIGNED DEFAULT 0,
  printer_total_total INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_total INTEGER UNSIGNED DEFAULT 0,
  scan_total_print INTEGER UNSIGNED DEFAULT 0,
  scan_scans INTEGER UNSIGNED DEFAULT 0,
  scan_fax_tx INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_scans INTEGER UNSIGNED DEFAULT 0,
  fecha_contador VARCHAR(20) DEFAULT '31/12/1900 11:59', 
  impresora VARCHAR(50) DEFAULT 'A1UG011006937',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS 363_A1UE011020415(
  con_id INTEGER unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(50) DEFAULT 'SIN ASIGNAR',
  total_counter INTEGER UNSIGNED DEFAULT 0,
  total_large_size_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_originals_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter INTEGER UNSIGNED DEFAULT 0,
  copy_total_total INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_total INTEGER UNSIGNED DEFAULT 0,
  printer_total_total INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_total INTEGER UNSIGNED DEFAULT 0,
  scan_total_print INTEGER UNSIGNED DEFAULT 0,
  scan_scans INTEGER UNSIGNED DEFAULT 0,
  scan_fax_tx INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_scans INTEGER UNSIGNED DEFAULT 0,
  fecha_contador VARCHAR(20) DEFAULT '31/12/1900 11:59', 
  impresora VARCHAR(50) DEFAULT 'A1UE011020415',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS 363_A1UE011024719(
  con_id INTEGER unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(50) DEFAULT 'SIN ASIGNAR',
  total_counter INTEGER UNSIGNED DEFAULT 0,
  total_large_size_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_originals_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter INTEGER UNSIGNED DEFAULT 0,
  copy_total_total INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_total INTEGER UNSIGNED DEFAULT 0,
  printer_total_total INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_total INTEGER UNSIGNED DEFAULT 0,
  scan_total_print INTEGER UNSIGNED DEFAULT 0,
  scan_scans INTEGER UNSIGNED DEFAULT 0,
  scan_fax_tx INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_scans INTEGER UNSIGNED DEFAULT 0,
  fecha_contador VARCHAR(20) DEFAULT '31/12/1900 11:59', 
  impresora VARCHAR(50) DEFAULT 'A1UE011024719',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS 363_A1UE011103699(
  con_id INTEGER unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(50) DEFAULT 'SIN ASIGNAR',
  total_counter INTEGER UNSIGNED DEFAULT 0,
  total_large_size_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_originals_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter INTEGER UNSIGNED DEFAULT 0,
  copy_total_total INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_total INTEGER UNSIGNED DEFAULT 0,
  printer_total_total INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_total INTEGER UNSIGNED DEFAULT 0,
  scan_total_print INTEGER UNSIGNED DEFAULT 0,
  scan_scans INTEGER UNSIGNED DEFAULT 0,
  scan_fax_tx INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_scans INTEGER UNSIGNED DEFAULT 0,
  fecha_contador VARCHAR(20) DEFAULT '31/12/1900 11:59', 
  impresora VARCHAR(50) DEFAULT 'A1UE011103699',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS 363_A1UE011016227(
  con_id INTEGER unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(50) DEFAULT 'SIN ASIGNAR',
  total_counter INTEGER UNSIGNED DEFAULT 0,
  total_large_size_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_originals_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter INTEGER UNSIGNED DEFAULT 0,
  copy_total_total INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_total INTEGER UNSIGNED DEFAULT 0,
  printer_total_total INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_total INTEGER UNSIGNED DEFAULT 0,
  scan_total_print INTEGER UNSIGNED DEFAULT 0,
  scan_scans INTEGER UNSIGNED DEFAULT 0,
  scan_fax_tx INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_scans INTEGER UNSIGNED DEFAULT 0,
  fecha_contador VARCHAR(20) DEFAULT '31/12/1900 11:59', 
  impresora VARCHAR(50) DEFAULT 'A1UE011016227',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS 363_A1UE011104367(
  con_id INTEGER unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(50) DEFAULT 'SIN ASIGNAR',
  total_counter INTEGER UNSIGNED DEFAULT 0,
  total_large_size_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_originals_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter INTEGER UNSIGNED DEFAULT 0,
  copy_total_total INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_total INTEGER UNSIGNED DEFAULT 0,
  printer_total_total INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_total INTEGER UNSIGNED DEFAULT 0,
  scan_total_print INTEGER UNSIGNED DEFAULT 0,
  scan_scans INTEGER UNSIGNED DEFAULT 0,
  scan_fax_tx INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_scans INTEGER UNSIGNED DEFAULT 0,
  fecha_contador VARCHAR(20) DEFAULT '31/12/1900 11:59', 
  impresora VARCHAR(50) DEFAULT 'A1UE011104367',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS 552_A2WV011008573(
  con_id INTEGER unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(50) DEFAULT 'SIN ASIGNAR',
  total_counter INTEGER UNSIGNED DEFAULT 0,
  total_large_size_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_originals_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter INTEGER UNSIGNED DEFAULT 0,
  copy_total_total INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_total INTEGER UNSIGNED DEFAULT 0,
  printer_total_total INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_total INTEGER UNSIGNED DEFAULT 0,
  scan_total_print INTEGER UNSIGNED DEFAULT 0,
  scan_scans INTEGER UNSIGNED DEFAULT 0,
  scan_fax_tx INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_scans INTEGER UNSIGNED DEFAULT 0,
  fecha_contador VARCHAR(20) DEFAULT '31/12/1900 11:59', 
  impresora VARCHAR(50) DEFAULT 'A2WV011008573',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS 283_A1UF012000896(
  con_id INTEGER unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(50) DEFAULT 'SIN ASIGNAR',
  total_counter INTEGER UNSIGNED DEFAULT 0,
  total_large_size_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_originals_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter INTEGER UNSIGNED DEFAULT 0,
  copy_total_total INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_total INTEGER UNSIGNED DEFAULT 0,
  printer_total_total INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_total INTEGER UNSIGNED DEFAULT 0,
  scan_total_print INTEGER UNSIGNED DEFAULT 0,
  scan_scans INTEGER UNSIGNED DEFAULT 0,
  scan_fax_tx INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_scans INTEGER UNSIGNED DEFAULT 0,
  fecha_contador VARCHAR(20) DEFAULT '31/12/1900 11:59', 
  impresora VARCHAR(50) DEFAULT 'A1UF012000896',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS 364e_A61F011024714(
  con_id INTEGER unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(50) DEFAULT 'SIN ASIGNAR',
  total_counter INTEGER UNSIGNED DEFAULT 0,
  total_large_size_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_originals_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter INTEGER UNSIGNED DEFAULT 0,
  duplex_print_counter INTEGER UNSIGNED DEFAULT 0,
  total_no_pages_output INTEGER UNSIGNED DEFAULT 0,
  copy_total_total INTEGER UNSIGNED DEFAULT 0,
  copy_total_full_color INTEGER UNSIGNED DEFAULT 0,
  copy_total_black INTEGER UNSIGNED DEFAULT 0,
  copy_total_2color INTEGER UNSIGNED DEFAULT 0,
  copy_total_single_color INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_total INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_full_color INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_black INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_2color INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_single_color INTEGER UNSIGNED DEFAULT 0,
  printer_total_total INTEGER UNSIGNED DEFAULT 0,
  printer_total_full_color INTEGER UNSIGNED DEFAULT 0,
  printer_total_black INTEGER UNSIGNED DEFAULT 0,
  printer_total_2color INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_total INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_full_color INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_black INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_2color INTEGER UNSIGNED DEFAULT 0,
  color_total_full_color INTEGER UNSIGNED DEFAULT 0,
  color_total_black INTEGER UNSIGNED DEFAULT 0,
  color_total_2color INTEGER UNSIGNED DEFAULT 0,
  color_total_single_color INTEGER UNSIGNED DEFAULT 0,
  color_large_size_full_color INTEGER UNSIGNED DEFAULT 0,
  color_large_size_black INTEGER UNSIGNED DEFAULT 0,
  color_large_size_2color INTEGER UNSIGNED DEFAULT 0,
  color_large_size_single_color INTEGER UNSIGNED DEFAULT 0,
  scan_total_print_full_color INTEGER UNSIGNED DEFAULT 0,
  scan_total_print_black INTEGER UNSIGNED DEFAULT 0,
  scan_total_scans INTEGER UNSIGNED DEFAULT 0,
  scan_total_fax_tx INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print_full_color INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print_black INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_scans INTEGER UNSIGNED DEFAULT 0,
  fecha_contador VARCHAR(20) DEFAULT '31/12/1900 11:59', 
  impresora VARCHAR(50) DEFAULT 'A61F011024714',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS C452_A0P2011001067(
  con_id INTEGER unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(50) DEFAULT 'SIN ASIGNAR',
  total_counter INTEGER UNSIGNED DEFAULT 0,
  total_large_size_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_originals_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter INTEGER UNSIGNED DEFAULT 0,
  copy_total_total INTEGER UNSIGNED DEFAULT 0,
  copy_total_full_color INTEGER UNSIGNED DEFAULT 0,
  copy_total_black INTEGER UNSIGNED DEFAULT 0,
  copy_total_2color INTEGER UNSIGNED DEFAULT 0,
  copy_total_single_color INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_total INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_full_color INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_black INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_2color INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_single_color INTEGER UNSIGNED DEFAULT 0,
  printer_total_total INTEGER UNSIGNED DEFAULT 0,
  printer_total_full_color INTEGER UNSIGNED DEFAULT 0,
  printer_total_black INTEGER UNSIGNED DEFAULT 0,
  printer_total_2color INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_total INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_full_color INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_black INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_2color INTEGER UNSIGNED DEFAULT 0,
  color_total_full_color INTEGER UNSIGNED DEFAULT 0,
  color_total_black INTEGER UNSIGNED DEFAULT 0,
  color_total_2color INTEGER UNSIGNED DEFAULT 0,
  color_total_single_color INTEGER UNSIGNED DEFAULT 0,
  color_large_size_full_color INTEGER UNSIGNED DEFAULT 0,
  color_large_size_black INTEGER UNSIGNED DEFAULT 0,
  color_large_size_2color INTEGER UNSIGNED DEFAULT 0,
  color_large_size_single_color INTEGER UNSIGNED DEFAULT 0,
  scan_total_print_full_color INTEGER UNSIGNED DEFAULT 0,
  scan_total_print_black INTEGER UNSIGNED DEFAULT 0,
  scan_total_scans INTEGER UNSIGNED DEFAULT 0,
  scan_total_fax_tx INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print_full_color INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print_black INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_scans INTEGER UNSIGNED DEFAULT 0,
  fecha_contador VARCHAR(20) DEFAULT '31/12/1900 11:59', 
  impresora VARCHAR(50) DEFAULT 'A0P2011001067',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS C554e_A5AY011013622(
  con_id INTEGER unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(50) DEFAULT 'SIN ASIGNAR',
  total_counter INTEGER UNSIGNED DEFAULT 0,
  total_large_size_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_originals_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter INTEGER UNSIGNED DEFAULT 0,
  duplex_print_counter INTEGER UNSIGNED DEFAULT 0,
  total_no_pages_output INTEGER UNSIGNED DEFAULT 0,
  copy_total_total INTEGER UNSIGNED DEFAULT 0,
  copy_total_full_color INTEGER UNSIGNED DEFAULT 0,
  copy_total_black INTEGER UNSIGNED DEFAULT 0,
  copy_total_2color INTEGER UNSIGNED DEFAULT 0,
  copy_total_single_color INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_total INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_full_color INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_black INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_2color INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_single_color INTEGER UNSIGNED DEFAULT 0,
  printer_total_total INTEGER UNSIGNED DEFAULT 0,
  printer_total_full_color INTEGER UNSIGNED DEFAULT 0,
  printer_total_black INTEGER UNSIGNED DEFAULT 0,
  printer_total_2color INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_total INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_full_color INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_black INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_2color INTEGER UNSIGNED DEFAULT 0,
  color_total_full_color INTEGER UNSIGNED DEFAULT 0,
  color_total_black INTEGER UNSIGNED DEFAULT 0,
  color_total_2color INTEGER UNSIGNED DEFAULT 0,
  color_total_single_color INTEGER UNSIGNED DEFAULT 0,
  color_large_size_full_color INTEGER UNSIGNED DEFAULT 0,
  color_large_size_black INTEGER UNSIGNED DEFAULT 0,
  color_large_size_2color INTEGER UNSIGNED DEFAULT 0,
  color_large_size_single_color INTEGER UNSIGNED DEFAULT 0,
  scan_total_print_full_color INTEGER UNSIGNED DEFAULT 0,
  scan_total_print_black INTEGER UNSIGNED DEFAULT 0,
  scan_total_scans INTEGER UNSIGNED DEFAULT 0,
  scan_total_fax_tx INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print_full_color INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print_black INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_scans INTEGER UNSIGNED DEFAULT 0,
  fecha_contador VARCHAR(20) DEFAULT '31/12/1900 11:59', 
  impresora VARCHAR(50) DEFAULT 'A5AY011013622',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS C227_A798011501042(
  con_id INTEGER unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(50) DEFAULT 'SIN ASIGNAR',
  total_counter INTEGER UNSIGNED DEFAULT 0,
  total_large_size_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_originals_counter INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter INTEGER UNSIGNED DEFAULT 0,
  duplex_print_counter INTEGER UNSIGNED DEFAULT 0,
  total_no_pages_output INTEGER UNSIGNED DEFAULT 0,
  duplex_print_rate FLOAT (10,5) DEFAULT 00000.00000,
  psc_a3 INTEGER UNSIGNED DEFAULT 0,
  psc_a4 INTEGER UNSIGNED DEFAULT 0,
  psc_b4 INTEGER UNSIGNED DEFAULT 0,
  psc_b5 INTEGER UNSIGNED DEFAULT 0,
  psc_55x85 INTEGER UNSIGNED DEFAULT 0,
  psc_85x11 INTEGER UNSIGNED DEFAULT 0,
  psc_85x14 INTEGER UNSIGNED DEFAULT 0,
  psc_11x17 INTEGER UNSIGNED DEFAULT 0,
  psc_long INTEGER UNSIGNED DEFAULT 0,
  psc_other INTEGER UNSIGNED DEFAULT 0,
  nin1_2in1 INTEGER UNSIGNED DEFAULT 0,
  nin1_4in1 INTEGER UNSIGNED DEFAULT 0,
  nin1_other INTEGER UNSIGNED DEFAULT 0,
  nin1_nin1printrate INTEGER UNSIGNED DEFAULT 0,
  copy_total_total INTEGER UNSIGNED DEFAULT 0,
  copy_total_full_color INTEGER UNSIGNED DEFAULT 0,
  copy_total_black INTEGER UNSIGNED DEFAULT 0,
  copy_total_2color INTEGER UNSIGNED DEFAULT 0,
  copy_total_single_color INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_total INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_full_color INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_black INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_2color INTEGER UNSIGNED DEFAULT 0,
  copy_large_size_single_color INTEGER UNSIGNED DEFAULT 0,
  copy_copypaper_allcolor INTEGER UNSIGNED DEFAULT 0,
  copy_copypaper_full_color INTEGER UNSIGNED DEFAULT 0,
  copy_copypaper_black INTEGER UNSIGNED DEFAULT 0,
  copy_copypaper_monobicolor INTEGER UNSIGNED DEFAULT 0,
  printer_total_total INTEGER UNSIGNED DEFAULT 0,
  printer_total_full_color INTEGER UNSIGNED DEFAULT 0,
  printer_total_black INTEGER UNSIGNED DEFAULT 0,
  printer_total_2color INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_total INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_full_color INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_black INTEGER UNSIGNED DEFAULT 0,
  printer_large_size_2color INTEGER UNSIGNED DEFAULT 0,
  printer_printpaper_allcolor INTEGER UNSIGNED DEFAULT 0,
  printer_printpaper_full_color INTEGER UNSIGNED DEFAULT 0,
  printer_printpaper_black INTEGER UNSIGNED DEFAULT 0,
  printer_printpaper_monobicolor INTEGER UNSIGNED DEFAULT 0,
  color_total_full_color INTEGER UNSIGNED DEFAULT 0,
  color_total_black INTEGER UNSIGNED DEFAULT 0,
  color_total_2color INTEGER UNSIGNED DEFAULT 0,
  color_total_single_color INTEGER UNSIGNED DEFAULT 0,
  color_large_size_full_color INTEGER UNSIGNED DEFAULT 0,
  color_large_size_black INTEGER UNSIGNED DEFAULT 0,
  color_large_size_2color INTEGER UNSIGNED DEFAULT 0,
  color_large_size_single_color INTEGER UNSIGNED DEFAULT 0,
  scan_total_print_full_color INTEGER UNSIGNED DEFAULT 0,
  scan_total_print_black INTEGER UNSIGNED DEFAULT 0,
  scan_total_scans INTEGER UNSIGNED DEFAULT 0,
  scan_total_fax_tx INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print_full_color INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_print_black INTEGER UNSIGNED DEFAULT 0,
  scan_large_size_scans INTEGER UNSIGNED DEFAULT 0,
  scan_printpaper_allcolor INTEGER UNSIGNED DEFAULT 0,
  scan_printpaper_full_color INTEGER UNSIGNED DEFAULT 0,
  scan_printpaper_black INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter_fullcolor INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter_black INTEGER UNSIGNED DEFAULT 0,
  no_of_prints_counter_monobiocolor INTEGER UNSIGNED DEFAULT 0,
  fecha_contador VARCHAR(20) DEFAULT '31/12/1900 11:59', 
  impresora VARCHAR(50) DEFAULT 'A798011501042',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);